fix(create-instance): Check volume is effectively attached before copying

diff --git a/.github/workflows/create-instance.yml b/.github/workflows/create-instance.yml
--- a/.github/workflows/create-instance.yml
+++ b/.github/workflows/create-instance.yml
@@ -446,6 +446,32 @@ jobs:
       - name: Copy installed files into attached volume
         id: copy_installed_files
         run: |
+          function check_mountpoint_ready {
+            ssh \
+              -o StrictHostKeyChecking=no \
+              -o UserKnownHostsFile=/dev/null \
+              -o LogLevel=ERROR \
+              exouser@$INSTANCE_IP \
+              'mountpoint -q /media/volume/MyData'
+          }
+          set +e
+          max_attempts=5
+          for attempt in $(seq 1 $max_attempts); do
+            echo "Checking if mount point is ready ($attempt/$max_attempts)"
+            check_mountpoint_ready
+            if check_mountpoint_ready; then
+              echo "Mount point /media/volume/MyData is ready."
+              break
+            else
+              echo "Mount point not ready. Retrying in 5 seconds..."
+              sleep 5
+            fi
+          done
+          if ! check_mountpoint_ready; then
+            echo "::error ::Mount point /media/volume/MyData not ready after $((max_attempts * 5)) seconds."
+            exit 1
+          fi
+          set -e
           ssh \
             -o StrictHostKeyChecking=no \
             -o UserKnownHostsFile=/dev/null \
